const sampleArr = [
  {
    key: "prod001",
    name: "Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation.",
    dimension: "10x8x3 cm",
    price: 99.99,
    category: "Audio",
    availability: true,
    Image: ["https://example.com/image1.jpg"],
  },
  {
    key: "prod002",
    name: "Smart LED Bulb",
    description: "WiFi-enabled LED bulb with color-changing options.",
    dimension: "5x5x10 cm",
    price: 29.99,
    category: "Light",
    availability: true,
    Image: ["https://example.com/image2.jpg"],
  },
  {
    key: "prod003",
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with deep bass.",
    dimension: "12x6x6 cm",
    price: 49.99,
    category: "Audio",
    availability: true,
    Image: ["https://example.com/image3.jpg"],
  },
  {
    key: "prod004",
    name: "Gaming Mouse",
    description: "Ergonomic gaming mouse with RGB lighting.",
    dimension: "13x7x4 cm",
    price: 39.99,
    category: "Accessories",
    availability: true,
    Image: ["https://example.com/image4.jpg"],
  },
  {
    key: "prod005",
    name: "Mechanical Keyboard",
    description: "Tactile mechanical keyboard for gamers and professionals.",
    dimension: "44x13x3 cm",
    price: 79.99,
    category: "Accessories",
    availability: true,
    Image: ["https://example.com/image5.jpg"],
  },
  {
    key: "prod006",
    name: "Smartwatch",
    description: "Feature-packed smartwatch with heart rate monitoring.",
    dimension: "4x4x1 cm",
    price: 149.99,
    category: "Wearables",
    availability: true,
    Image: ["https://example.com/image6.jpg"],
  },
  {
    key: "prod007",
    name: "USB-C Hub",
    description: "Multi-port USB-C hub with HDMI and Ethernet.",
    dimension: "10x5x2 cm",
    price: 59.99,
    category: "Accessories",
    availability: true,
    Image: ["https://example.com/image7.jpg"],
  },
  {
    key: "prod008",
    name: "External SSD",
    description: "1TB external SSD with high-speed transfer.",
    dimension: "8x5x1 cm",
    price: 129.99,
    category: "Storage",
    availability: true,
    Image: ["https://example.com/image8.jpg"],
  },
  {
    key: "prod009",
    name: "4K Monitor",
    description: "27-inch 4K UHD monitor with HDR support.",
    dimension: "62x36x5 cm",
    price: 299.99,
    category: "Display",
    availability: true,
    Image: ["https://example.com/image9.jpg"],
  },
  {
    key: "prod010",
    name: "Wireless Charger",
    description: "Fast wireless charging pad for smartphones.",
    dimension: "10x10x1 cm",
    price: 34.99,
    category: "Accessories",
    availability: true,
    Image: ["https://example.com/image10.jpg"],
  },
  {
    key: "prod011",
    name: "Noise Cancelling Earbuds",
    description: "True wireless earbuds with active noise cancellation.",
    dimension: "3x2x2 cm",
    price: 129.99,
    category: "Audio",
    availability: true,
    Image: ["https://example.com/image11.jpg"],
  },
  {
    key: "prod012",
    name: "Smart Plug",
    description: "WiFi-enabled smart plug with energy monitoring.",
    dimension: "6x6x4 cm",
    price: 19.99,
    category: "Smart Home",
    availability: true,
    Image: ["https://example.com/image12.jpg"],
  },
  {
    key: "prod013",
    name: "VR Headset",
    description: "Immersive virtual reality headset for gaming.",
    dimension: "20x10x12 cm",
    price: 249.99,
    category: "Gaming",
    availability: true,
    Image: ["https://example.com/image13.jpg"],
  },
  {
    key: "prod014",
    name: "Dash Cam",
    description: "HD dash cam with night vision and loop recording.",
    dimension: "8x6x4 cm",
    price: 89.99,
    category: "Automotive",
    availability: true,
    Image: ["https://example.com/image14.jpg"],
  },
  {
    key: "prod015",
    name: "Action Camera",
    description: "Waterproof action camera with 4K recording.",
    dimension: "6x4x3 cm",
    price: 199.99,
    category: "Cameras",
    availability: true,
    Image: ["https://example.com/image15.jpg"],
  },
];

export default sampleArr;
